var filesUrls='D:/worktwo/mes/mes-base/files/';
$(function(){
	//搜索条件
	var tableSearchData=[];
	var mainSearchData=[{
		idName:'comboPlant',
		text:'工厂',
		comboUrl:'/base/plant/publicPlantSelect',
		comboId:'tmBasPlantId',
		comboText:'plant',
		field:'tmBasPlantId',
		onClick:function(data){
			$('#comboWorkshop').val();
			$('#comboLine').val();
			$('#comboUloc').val();
			Ew.selectLink({
		        comboUrl:'/base/workshop/publicWorkshopSelect',
		        comboData:JSON.stringify({tmBasPlantId:data.id}),
		        id:['comboWorkshop'],
		        comboId:'tmBasWorkshopId',
		        comboText:'workshop'
		    });
			Ew.selectLink({
				comboUrl:'/base/line/publicLineSelect',
				comboData:JSON.stringify({tmBasPlantId:data.id}),
				id:['comboLine'],
				comboId:'tmBasLineId',
				comboText:'line'
			});
			Ew.selectLink({
				comboUrl:'/base/uloc/queryUlocSelectForInputWithLineId',
				comboData:JSON.stringify({pTmBasPlantId:data.id}),
				id:['comboUloc'],
				comboId:'tmBasUlocId',
				comboText:'ulocNo'
			});
		}
	},{
		idName:'comboWorkshop',
		text:'车间',
		comboUrl:'/base/workshop/publicWorkshopSelect',
		comboId:'tmBasWorkshopId',
		comboText:'workshop',
		field:'tmBasWorkshopId',
		onClick:function(data){
			Ew.selectLink({
		        comboUrl:'/base/line/publicLineSelect',
		        comboData:JSON.stringify({tmBasWorkshopId:data.id}),
		        id:['comboLine'],
		        comboId:'tmBasLineId',
		        comboText:'line'
		    });
			Ew.selectLink({
				comboUrl:'/base/uloc/queryUlocSelectForInputWithLineId',
				comboData:JSON.stringify({wTmBasWorkshopId:data.id}),
				id:['comboUloc'],
				comboId:'tmBasUlocId',
				comboText:'ulocNo'
			});
		}
	},{
		idName:'comboLine',
		text:'产线',
		comboUrl:'/base/line/publicLineSelect',
		comboId:'tmBasLineId',
		comboText:'line',
		field:'tmBasLineId',
		onClick:function(data){
			Ew.selectLink({
				comboUrl:'/base/uloc/queryUlocSelectForInputWithLineId',
				comboData:JSON.stringify({lTmBasLineId:data.id}),
				id:['comboUloc'],
				comboId:'tmBasUlocId',
				comboText:'ulocNo'
			});
		}
	
	},{
		idName:'comboUloc',
		text:'工位',
		comboUrl:'/base/uloc/queryUlocSelectForInputWithLineId',
		comboData:{
			id:['comboPlant','comboWorkshop','comboLine'],
			field:['pTmBasPlantId','wTmBasWorkshopId','lTmBasLineId'],
			other:{}
		},
		comboId:'tmBasUlocId',
		comboText:'ulocNo',
		field:'tmBasUlocId',
		valid:['notEmpty'],
		isSearch:true
	},{
		idName:'inputComSN',
		text:'SN',
		comboUrl:"/order/ppordersn/querySn",
		comboId:'sn',
		comboText:'sn',
		field:'sn',
		onClick:function(data){
			if($('#comboUloc').val()==null||$('#comboUloc').val()==""){
				Ew.layer.msg('请选择工位！',{icon:7,time:1000});
				$('#inputComSN').val('');
				return
			}
			$('#comboOrder').val('');
			$('#textPart').val('');
			Ew.selectLink({
		        comboUrl:"/order/ppordersn/queryOrder",
		        comboData:JSON.stringify({sn:data}),
		        id:['comboOrder'],
		        comboId:'ttPpOrderId',
		        comboText:'order_no',
		        onSuccess:function(data){
		        	if(data.length<1){
		        		Ew.layer.msg('未查询到数据！',{icon:7,time:1000});
		        		return;
		        	}else if(data.length==1){
		        		$('#textPart').val(data[0].part_name);
		        		$.ajax({
		        			   type: "POST",
		        			   url:apiUrl+'/order/ppordersn/queryRouteAndpart',
		        			   data:JSON.stringify({'ttPpOrderId':data[0].ttPpOrderId,'sn':data[0].sn}),
		        			   contentType:'application/json;charset=UTF-8',
		        			   success: function(results){
		   	        			if(results.results.length>0){
			        				 tableSearchData={'tmBasUlocId':$('#comboUloc').val(),'tmBasRouteId':results.results[0].tmBasRouteId,'tmBasPartId':results.results[0].tmBasPartId};
			        				 $('#table1').bootstrapTable('refresh');
			        				
			        			}
		    			   }
		        			});
		        		}
		        }
		    });
			
		}
	
	},{
		idName:'comboOrder',
		text:'订单编号',
		comboUrl:"",
		comboId:'ttPpOrderId',
		comboText:'order',
		field:'ttPpOrderId',
		onClick:function(data){
			if($('#comboUloc').val()==null||$('#comboUloc').val()==""){
				Ew.layer.msg('请选择工位！',{icon:2,time:1000});
				$('#comboOrder').val('');
				return
			}
		        		$.ajax({	
		        				type:"POST",
		        			   url:apiUrl+'/order/ppordersn/queryRouteAndpart',
		        			   data:JSON.stringify({'ttPpOrderId':data[0].ttPpOrderId,'sn':data[0].sn}),
		        			   contentType:'application/json;charset=UTF-8',
		        			   success: function(results){
		        			   	$('#textPart').val(results.results[0].part_no);
		   	        			if(results.results.length>0){
			        				 tableSearchData={'tmBasUlocId':$('#comboUloc').val(),'tmBasRouteId':results.results[0].tmBasRouteId,'tmBasPartId':results.results[0].tmBasPartId};
			        				   $('#table1').bootstrapTable('refresh');
			        			}
		    			   }
		        		});
		        		}
	},{
		idName:'textPart',
		text:'产品',
		disabled:true
	}];
	
	Ew.search('.demoSearch',{
		title:'查询',
		textValues:mainSearchData
		
	});

	
//工艺内容表格
	Ew.table('.demoTable',{
		btnValues:[],
		tableId:'table1',
		tableValue:{
			searchParams:tableSearchData,
			queryParams:function(){
				return tableSearchData;
			},
			nohidden:true,
			url:"/base/uloccontent/queryContent",
			columns:[{
				field:'step',
				title:'工序步骤',
				align:'center',
				sortable:true,
				 width:'120px'
			},
			{
				field:'userInstrument',
				title:'使用工具',
				align:'center',
				 width:'120px'
			},
			{
				field:'stepContent',
				title:'工序内容',
				align:'center',
				width:'120px'
			},
			{
				field:'stepRequirement',
				title:'技术要求',
				align:'center',
				width:'120px'
			},
			{
				field:'times',
				title:'次数',
				align:'center',
				width:'120px'
			},
			{
				field:'standardHour',
				title:'标准工时(分钟)',
				align:'center',
				width:'120px'
			}
			
			]
		}
	});
});

	